source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.0'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'

# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.4.4'

# Use Puma as the app server
gem 'puma', '~> 4.3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Use Authenticate
gem 'devise'

# Use create json
gem 'active_model_serializers'

# Use create seed data
gem 'seed-fu'

# Use for localize
gem 'rails-i18n'
gem 'devise-i18n'
gem 'devise-i18n-views'

# Use manage config data
gem 'config'

group :development, :test do
  # Use for debug
  gem 'pry-rails'

  # Use rspec test
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  # Use for debug
  gem 'pry-rails'

  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
